In [1]:
import os
import pandas as pd

In [6]:
# Ensure GCP credentials are visible to pandas
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../secrets/sa-key.json"

BUCKET_NAME = "ecommerce-raw-data-mohammed"

In [8]:
# Stream Parquet files directly from GCS into DataFrames
df_meta = pd.read_parquet(f"gs://{BUCKET_NAME}/raw/metadata/all_beauty_metadata.parquet")
df_meta.head(5)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Beauty,"Howard LC0008 Leather Conditioner, 8-Ounce (4-...",4.8,10,[],[],None,"{'hi_res': array([None,\n 'https://m.med...","{'title': array([], dtype=object), 'url': arra...",Howard Products,[],"{""Package Dimensions"": ""7.1 x 5.5 x 3 inches; ...",B01CUPMQZE,NaN,NaN,NaN
1,All Beauty,Yes to Tomatoes Detoxifying Charcoal Cleanser ...,4.5,3,[],[],None,{'hi_res': array(['https://m.media-amazon.com/...,"{'title': array([], dtype=object), 'url': arra...",Yes To,[],"{""Item Form"": ""Powder"", ""Skin Type"": ""Acne Pro...",B076WQZGPM,NaN,NaN,NaN
2,All Beauty,Eye Patch Black Adult with Tie Band (6 Per Pack),4.4,26,[],[],None,"{'hi_res': array([None, None], dtype=object), ...","{'title': array([], dtype=object), 'url': arra...",Levine Health Products,[],"{""Manufacturer"": ""Levine Health Products""}",B000B658RI,NaN,NaN,NaN
3,All Beauty,"Tattoo Eyebrow Stickers, Waterproof Eyebrow, 4...",3.1,102,[],[],None,{'hi_res': array(['https://m.media-amazon.com/...,"{'title': array([], dtype=object), 'url': arra...",Cherioll,[],"{""Brand"": ""Cherioll"", ""Item Form"": ""Powder"", ""...",B088FKY3VD,NaN,NaN,NaN
4,All Beauty,Precision Plunger Bars for Cartridge Grips – 9...,4.3,7,['Material: 304 Stainless Steel; Brass tip'\n ...,['The Precision Plunger Bars are designed to w...,None,"{'hi_res': array([None], dtype=object), 'large...","{'title': array([], dtype=object), 'url': arra...",Precision,[],"{""UPC"": ""644287689178""}",B07NGFDN6G,NaN,NaN,NaN

In [13]:
# --- Metadata Inspection ---
print("=== METADATA SHAPE ===")
print(df_meta.shape)

=== METADATA SHAPE ===
(50, 16)

In [15]:
print("\n=== METADATA COLUMNS & TYPES ===")
print(df_meta.dtypes)

=== METADATA COLUMNS & TYPES ===
main_category          str
title                  str
average_rating     float64
rating_number        int64
features               str
description            str
price                  str
images                 str
videos                 str
store                  str
categories             str
details                str
parent_asin            str
bought_together        str
subtitle               str
author                 str
dtype: object

In [16]:
print("\n=== METADATA NULL VALUES ===")
print(df_meta.isnull().sum())

=== METADATA NULL VALUES ===
main_category       0
title               0
average_rating      0
rating_number       0
features            0
description         0
price               0
images              0
videos              0
store               5
categories          0
details             0
parent_asin         0
bought_together    50
subtitle           50
author             50
dtype: int64

In [12]:
df_reviews = pd.read_parquet(f"gs://{BUCKET_NAME}/raw/reviews/all_beauty_reviews.parquet")
df_reviews.head(5)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Such a lovely scent but not overpowering.,This spray is really nice. It smells really go...,[],B00YQ6X8EO,B00YQ6X8EO,AGKHLEW2SOWHNMFQIJGBECAF7INQ,1588687728923,0,True
1,4.0,Works great but smells a little weird.,"This product does what I need it to do, I just...",[],B081TJ8YS3,B081TJ8YS3,AGKHLEW2SOWHNMFQIJGBECAF7INQ,1588615855070,1,True
2,5.0,Yes!,"Smells good, feels great!",[],B07PNNCSP9,B097R46CSY,AE74DYR3QUGVPZJ3P7RFWBGIX7XQ,1589665266052,2,True
3,1.0,Synthetic feeling,Felt synthetic,[],B09JS339BZ,B09JS339BZ,AFQLNQNQYFWQZPJQZS6V3NZU4QBQ,1643393630220,0,True
4,5.0,A+,Love it,[],B08BZ63GMJ,B08BZ63GMJ,AFQLNQNQYFWQZPJQZS6V3NZU4QBQ,1609322563534,0,True

In [18]:
# --- Reviews Inspection ---
print("\n=== REVIEWS SHAPE ===")
print(df_reviews.shape)

=== REVIEWS SHAPE ===
(50, 10)

In [19]:

print("\n=== REVIEWS RATING DISTRIBUTION ===")
print(df_reviews['rating'].value_counts(dropna=False))

=== REVIEWS RATING DISTRIBUTION ===
rating
5.0    29
3.0     8
4.0     5
1.0     5
2.0     3
Name: count, dtype: int64